### ISSUE TITLE
感谢作者开源，提几个疑问

### ISSUE THREAD

**Issue by ju0632** [FleyX/bookmark#1]
360急速浏览器导出的html书签文件导入失败，约5.5MB（我把书签文件导入了chrome，然后从chrome导出，在本站导入时依然失败）
没注意看作者只测试了 chrome抱歉
下面提几个疑问

1.搜索按钮会直达第一个结果
2.光标离开搜索框时，搜索结果列表能否自动缩回
3.添加书签如没有http(s)前缀，访问时重定向错误
4.添加书签时，添加url后能否自动获取标题名称
5.可否获取网址图标呢（非刚需）
6.后台管理的地址是什么啊
7.个人资料页面无法进入

**Comment by ju0632** [comment]
没注意看作者只测试了 chrome抱歉
下面提几个疑问
1. 搜索按钮会直达第一个结果
2.光标离开搜索框时，搜索结果列表能否自动缩回
3.添加书签如没有http(s)前缀，访问时重定向错误
4.可否获取网址图标呢（非刚需）

**Comment by ju0632** [comment]
https://github.com/luchenqun/my-bookmark，供作者参考看有需要借鉴的吗

**Comment by FleyX** [comment]
1.目前检索的默认选中项是第一个
2.可以考虑加上
3.未做自动添加前缀的功能，可以考虑加上
4.可以实现
5.可以实现
6.还没做呢
7.还没做呢

前一段时间由于换工作比较忙就没有继续开发，现在正在逐步做。

下面你提到的网站我是看了它的后才想要做这样一个东西的，本项目属于一个react和多模块springboot的练手项目，当然我也会持续更新的。

**Comment by FleyX** [comment]
可否把导入失败的书签文件发给我测试，邮箱：fanxb.tl@gmail.com

**Comment by ju0632** [comment]
邮件已发送 请测试 ju0632@qq.com

**Comment by FleyX** [comment]
ok,我会尽快测试的



fanxb.tl@gmail.com
 
发件人： Ju0632
发送时间： 2019-11-12 10:07
收件人： FleyX/bookmark
抄送： FleyX; Comment
主题： Re: [FleyX/bookmark] 感谢作者开源，提几个疑问 (#1)
邮件已发送 请测试 ju0632@qq.com

**Comment by FleyX** [comment]
已修复html文件解析错误的bug，同时服务器地址迁移到了国内地址west.tapme.top:8083,已做重定向

**Comment by ju0632** [comment]
给力！看到了
1、头像显示太大了，有些突兀
2、底部链接不是在新标签页打开，且与使用帮助相重合
