### ISSUE TITLE
mac系统chrome版本91无法安装插件

### ISSUE THREAD

**Issue by cnbillsomeday** [FleyX/bookmark#20]
<img width="500" alt="Snipaste_2021-07-08_11-56-59" src="https://user-images.githubusercontent.com/43331044/124860124-b7d9b300-dfe3-11eb-8fb6-6b93d08b5d95.png">
<img width="685" alt="Snipaste_2021-07-08_11-57-11" src="https://user-images.githubusercontent.com/43331044/124860158-c45e0b80-dfe3-11eb-84f1-c610584cf1ca.png">

**Comment by FleyX** [comment]
抱歉，插件未开发完毕，还不能使用

在 2021年7月8日，11:58，cnbill ***@***.***> 写道：

﻿

[Snipaste_2021-07-08_11-56-59]<https://user-images.githubusercontent.com/43331044/124860124-b7d9b300-dfe3-11eb-8fb6-6b93d08b5d95.png>

[Snipaste_2021-07-08_11-57-11]<https://user-images.githubusercontent.com/43331044/124860158-c45e0b80-dfe3-11eb-84f1-c610584cf1ca.png>

**Comment by FleyX** [comment]
浏览器插件可以用了哦，实现了右键新增书签
