### ISSUE TITLE
你好，我想添加或者将现有的搜索引擎（谷歌、bing、百度）改为其他的搜索引擎，应该在代码哪个地方修改。

### ISSUE THREAD

**Issue by cnbillsomeday** [FleyX/bookmark#43]
你好，我想添加或者将现有的搜索引擎（谷歌、bing、百度）改为其他的搜索引擎，应该在代码哪个地方修改。

**Comment by FleyX** [comment]
那不如我添加一个自定义搜索引擎的功能获取Outlook for Android

**Comment by FleyX** [comment]
功能已增加
https://github.com/FleyX/bookmark/releases/tag/1.3
