### ISSUE TITLE
使用配置文件

### ISSUE THREAD

**Issue by NoverNobida** [FleyX/bookmark#5]
希望在部署时可以使用 `.env` 配置文件来部署，一方面减少麻烦，另一方面，在遇到密码里面有特殊符号（比我的SMTP密码里面有 `^` ），会导致这个变量错误。另外，请问这个SMTP设置之后如何使用？似乎没有看到相关设置。请问有管理员页面吗？

**Comment by FleyX** [comment]
1.  目前没有增加从配置文件的计划，如果觉得麻烦可以将export 语句写到一个sh脚本中，执行命令：`source 脚本名`即可配置到系统中去
2. 特殊字符导致变量错误是指docker-compose读取错误，还是什么？
3. smpt用于发送邮件（比如验证码、消息通知），目前只在重置密码时用到
4. 目前没有管理员页面，个人精力、时间有限没有太多的时间来完整本项目

**Comment by NoverNobida** [comment]
@FleyX 就是 `export SMTP_PASSWORD=******` 的时候，密码带有特殊字符。

**Comment by FleyX** [comment]
@NoverNobida 加上引号应该能解决你的问题。比如：

```bash
export test='asdf^&&*((*&^@*&#($'
```
![image](https://user-images.githubusercontent.com/29558551/84593385-965cd500-ae7e-11ea-8c55-5c4ef74006c4.png)

**Comment by NoverNobida** [comment]
@FleyX 会出现另外的错误。
![image](https://user-images.githubusercontent.com/46912250/84598276-2eb58280-ae9c-11ea-9825-5da59f1dea19.png)
我的密码是这个样子的，所以应该是密码和语句混淆了。
![image](https://user-images.githubusercontent.com/46912250/84598252-fada5d00-ae9b-11ea-9679-0403ffad6192.png)

**Comment by FleyX** [comment]
好的，那就是docker-compose.yml写的有问题，今晚我会修改

**Comment by FleyX** [comment]
@NoverNobida 已修复[fd3538d](https://github.com/FleyX/bookmark/commit/fd3538d11f9cd44a979831c42a1d8dbd3530b00d)
